version: '3.9'

services:
  web:
    build: .
    container_name: python_app
    command: python src/app.py
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1